### ISSUE TITLE
Old ansible-role-oracle-java dependency

### ISSUE THREAD

**Issue by damselem** [lifeofguenter/ansible-role-unifi-controller#2]
Hi,

Is there any special reason why both this role and the ansible-role-unifi-video have a dependency on ansible-role-oracle-java 0.1.21 and 0.1.20 respectively? I see that there's already version 0.5.2

**Comment by lifeofguenter** [comment]
no reason, can/should be updated :) - you can always override that behaviour though

**Comment by damselem** [comment]
Thanks. I switched to a Docker based solution, but definitely good to know it can be overridden.

**Comment by lifeofguenter** [comment]
fixed in latest version
